name: Roku TV Swipe Card
description: Roku TV Swipe Card
version: 0.0.4
type: lovelace
keywords:
  - roku
  - tvcard
  - remote
  - tv
  - television
author:
  name: slaterdavid12
contributors:
  - name: usernein
  - name: Nerwyn
  - name: mar_robHD
license: Apache License, Version 2.0
files:
  - roku-tv-card.js
  - roku-tv-card-editor.js
